### ISSUE TITLE
LOGOUT and JWT token invalidation

### ISSUE THREAD

**Issue by massimilianoporzio** [devsar/django-graphene-vuejs#1]
How to effectively logout a user? I mean that his token is still valid!

**Comment by edvm** [comment]
@massimilianoporzio Hi! 
Add a `revokeToken` to the mutations on the root schema:
![image](https://user-images.githubusercontent.com/689275/62800158-1d9c2800-bab9-11e9-9666-771f98d7ca80.png)

Then you can revoke the token using the mutation:
```
mutation RevokeToken($token:String!) {
  revokeToken(refreshToken: $token) {
    revoked
  }
}
```

Be sure to have `graphql_jwt.refresh_token.apps.RefreshTokenConfig` in your `INSTALLED_APPS` (settings.py) https://django-graphql-jwt.domake.io/en/stable/refresh_token.html#long-running-refresh-tokens

Here is the link to the docs:
https://buildmedia.readthedocs.org/media/pdf/django-graphql-jwt/latest/django-graphql-jwt.pdf

**Comment by massimilianoporzio** [comment]
Please i need a working example of sign in log in and logout using jwt on a cookie... Can u help me? I am planning to use vue as front-end Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Da: Emiliano Dalla Verde Marcozzi <notifications@github.com>Data: Oggi alle 20:20A: devsar/django-graphene-vuejs <django-graphene-vuejs@noreply.github.com>Cc: massimilianoporzio <massimiliano.porzio@gmail.com>, Mention <mention@noreply.github.com>Oggetto: Re: [devsar/django-graphene-vuejs] LOGOUT and JWT token invalidation (#1)@massimilianoporzio Hi!
Add a revokeToken to the mutations on the root schema:

Here is the link to the docs:
https://buildmedia.readthedocs.org/media/pdf/django-graphql-jwt/latest/django-graphql-jwt.pdf
